services:
  - name: feelmitra
    type: web
    env: python
    buildCommand: "pip install --upgrade pip && pip install --no-strip-extras -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 8000"
    plan: free
    envVars:
      - key: FRONTEND_URL
        value: "http://localhost:3000"  # Replace with your frontend's URL