services:
  - name: feelmitra
    type: web
    runtime: python
    repo: https://github.com/aman5874/feelmitrabackend
    plan: free
    envVars:
      - key: NEXTAUTH_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: PROJECT_REF
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"